In [1]:
import torch

In [2]:
torch.__version__

'2.1.1+cpu'

In [3]:
# Scaller
scaller = torch.tensor(7)
scaller

tensor(7)

In [4]:
scaller.ndim

0

In [5]:
scaller.item()

7

In [7]:
# Vector
vector = torch.tensor([
    4, 7
])
vector

tensor([4, 7])

In [17]:
vector.ndim, vector.shape

(1, torch.Size([2]))

In [19]:
# Matrix
matrix = torch.tensor([
    [7,7],
    [6,7]
])
matrix

tensor([[7, 7],
        [6, 7]])

In [20]:
matrix.ndim, matrix.shape

(2, torch.Size([2, 2]))

In [21]:
# Tensor
tensor = torch.tensor([[
    [2,5,2],
    [4,6,7],
    [1,2,3]
]])

In [22]:
tensor.ndim

3

In [23]:
tensor.shape

torch.Size([1, 3, 3])

In [26]:
tensor[0]

tensor([[2, 5, 2],
        [4, 6, 7],
        [1, 2, 3]])

________

In [28]:
# random tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9159, 0.4094, 0.7690, 0.6076],
        [0.8284, 0.6805, 0.1700, 0.7154],
        [0.5140, 0.6418, 0.7337, 0.8432]])

In [36]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 224, 224]))

In [42]:
# Zeros and Ones
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [50]:
ones = torch.ones(3, 4, dtype=torch.int8)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int8)

In [51]:
ones.dtype

torch.int8

In [54]:
# Range
torch.range(0, 3)

C:\Users\MBR\AppData\Local\Temp\ipykernel_23112\3005455003.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 3)


tensor([0., 1., 2., 3.])

In [56]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
# Tensor Like other Tensor shape
zeros = torch.zeros_like(one_to_ten)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
# Tensor data Types
float_default_tensor = torch.tensor([3.3, 3, 5.2], dtype=None)
float_default_tensor

tensor([3.3000, 3.0000, 5.2000])

In [64]:
float_default_tensor.dtype

torch.float32

In [66]:
float_16_tensor = float_default_tensor.type(torch.float16)
float_16_tensor

tensor([3.3008, 3.0000, 5.1992], dtype=torch.float16)

In [74]:
float_16_tensor * float_default_tensor

tensor([10.8926,  9.0000, 27.0359])

In [83]:
# Getting information from a Tensor
some_tensor = torch.rand((3,4))
some_tensor

tensor([[0.5974, 0.8667, 0.5128, 0.3410],
        [0.0420, 0.2214, 0.9261, 0.1991],
        [0.9922, 0.0454, 0.8602, 0.4057]])

In [84]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5974, 0.8667, 0.5128, 0.3410],
        [0.0420, 0.2214, 0.9261, 0.1991],
        [0.9922, 0.0454, 0.8602, 0.4057]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


___

In [91]:
# Manipulating Tensors
tensor = torch.tensor([1, 3, 5])
tensor + 10

tensor([11, 13, 15])

In [92]:
tensor * 10

tensor([10, 30, 50])

In [93]:
tensor - 10

tensor([-9, -7, -5])

In [122]:
# Min, Max, Mean and sum Tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [95]:
x.min()

tensor(0)

In [96]:
x.max()

tensor(90)

In [104]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [106]:
torch.sum(x)

tensor(450)

In [108]:
# Finding the positional min and max
x.argmin()

tensor(0)

In [109]:
x.argmax()

tensor(9)

In [123]:
# Reshaping, Viewing, and stacking Tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [117]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [124]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [125]:
z[:, 0] = 8
z, x

(tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([8., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [126]:
x_stacked = torch.vstack([x, x, x, x])
x_stacked

tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.],
        [8., 2., 3., 4., 5., 6., 7., 8., 9.],
        [8., 2., 3., 4., 5., 6., 7., 8., 9.],
        [8., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [134]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[8., 8., 8., 8.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

___

In [14]:
import torch
import numpy as np

In [4]:
# Selecting data from Tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [5]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
x[0][0]

tensor([1, 2, 3])

In [13]:
x[:, 1, 1]

tensor([5])

In [21]:
# PyTorch tensor and Numpy
array = np.arange(1., 8.)
tensor = torch.from_numpy(array).type(torch.float32)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [23]:
tensor = torch.ones(7)
tensor_to_numpy = tensor.numpy()

In [24]:
tensor_to_numpy

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [33]:
# Reproducbility
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(f"""If random_tensor_A,\n{random_tensor_A} 
        \n== random_tensor_B,\n{random_tensor_B}??
        \n{random_tensor_A == random_tensor_B}""")

If random_tensor_A,
tensor([[0.8475, 0.2964, 0.3045, 0.4173],
        [0.1376, 0.1171, 0.7701, 0.2474],
        [0.0398, 0.3448, 0.8498, 0.5680]]) 
        
== random_tensor_B,
tensor([[0.3132, 0.1213, 0.3685, 0.9390],
        [0.1216, 0.4378, 0.9013, 0.8835],
        [0.3341, 0.1700, 0.9073, 0.1720]])??
        
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [38]:
RANDOM_SEED = 22
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(f"""If random_tensor_C,\n{random_tensor_C} 
        \n== random_tensor_D,\n{random_tensor_D}??
        \n{random_tensor_C == random_tensor_D}""")

If random_tensor_C,
tensor([[0.3659, 0.7025, 0.3104, 0.0097],
        [0.6577, 0.1947, 0.9506, 0.6887],
        [0.8174, 0.7575, 0.7492, 0.6874]]) 
        
== random_tensor_D,
tensor([[0.3659, 0.7025, 0.3104, 0.0097],
        [0.6577, 0.1947, 0.9506, 0.6887],
        [0.8174, 0.7575, 0.7492, 0.6874]])??
        
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [39]:
torch.cuda.is_available()

False

In [41]:
!nvidia-smi

Wed Jul 31 21:43:40 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.13                 Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650 ...  WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   76C    P0              14W /  35W |      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [44]:
# Putting models and tensors  on and off GPU
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device

device(type='cpu')

In [45]:
tensor = torch.tensor([1, 2, 3]).to(device)
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

if the tensor putting on cuda and you need to transfer it to numpy array
* use `cpu()` function to reset it on cpu.
* then use `numpy` to transfer the tensor to numpy array.
```python
tensor_on_GPU = torch.tensor([1, 2, 3]).to("cuda")
tensor_on_CPU = tensor_on_GPU.cpu().numpy()
```